server:
  port: 8765
  error:
    include-stacktrace: never
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          jwk-set-uri: ${JWKS_URI}
  cloud:
    gateway:
      #      loadbalancer:
      #        use404: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
#            allowedOrigins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
#            allowedOrigins: "*"
#            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-justedlevhub
          uri: lb://users-justedlevhub
          predicates:
            - Path=/**
        - id: jstorage-service
          uri: lb://jstorage-service
          predicates:
            - Path=/**
        - id: jtascexec-service
          uri: lb://jtascexec-service
          predicates:
            - Path=/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/**
#        - id: swagger_route
#          uri: http://localhost:${server.port}/v3/api-docs
#          predicates:
#            - Path=/swagger/**
#          filters:
#            - RewritePath=/swagger/(?<segment>.*), /$\{segment}
#      default-filters:
#        TokenRelay=
#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: j-provider
#            client-id: gateway-client-id
#            client-secret: secret_justedlev
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:${server.port}/login/oauth2/code/{registrationId}"
#            scope: openid, message.read
#        provider:
#          j-provider:
#            issuer-uri: http://localhost:9876
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${DISCOVERY_HOST}
logging:
  level:
    web: debug
    org:
      springframework:
        security: trace

# Custom properties
keycloak:
  issuer-uri: ${ISSUER_URI}
  jwt-set-uri: ${JWKS_URI}
  jwt-converter:
    role-claim-names: realm_access.roles,resource_access.account.roles
    principal-claim-name: preferred_username