server:
  port: 8765
  error:
    include-stacktrace: never

spring:
  application:
    name: '@project.name@'
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
      roles: ${ROLES}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}
        opaquetoken:
          introspection-uri: ${KEYCLOAK_INTROSPECTION_ENDPOINT}
          client-id: ${KEYCLOAK_CLIENT_ID}
          client-secret: ${KEYCLOAK_CLIENT_SECRET}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
            allowed-headers: '*'
            allowed-methods: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: users.justedlev.hub
          uri: lb://users.justedlev.hub
          predicates:
            - Path=/users/api/**
        - id: notifications.justedlev.hub
          uri: lb://notifications.justedlev.hub
          predicates:
            - Path=/notifications/api/**
#        - id: jstorage-service
#          uri: lb://jstorage-service
#          predicates:
#            - Path=/**
#        - id: jtascexec-service
#          uri: lb://jtascexec-service
#          predicates:
#            - Path=/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /v3/api-docs
        name: 'Api Gateway'
      - url: /users.justedlev.hub/api/v3/api-docs
        name: 'Accounts Service APIs'
      - url: /notifications.justedlev.hub/api/v3/api-docs
        name: 'Notifications Service APIs'

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${DISCOVERY_HOST}

logging:
  level:
    web: debug
    org:
      springframework:
        security: trace

# Custom properties
