server:
  port: 8765
  error:
    include-stacktrace: never

spring:
  application:
    name: '@project.name@'
  devtools:
    restart:
      enabled: false
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
      roles: ${ROLES}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
          jwk-set-uri: ${keycloak.jwk-set-uri}
        opaquetoken:
          introspection-uri: ${keycloak.introspection-uri}
          client-id: ${keycloak.client.id}
          client-secret: ${keycloak.client.secret}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
            allowed-headers: '*'
            allowed-methods: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/api/**

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - url: /v3/api-docs
        name: 'API Gateway'
        display-name: 'API Gateway'
      - url: /users-service/api/v3/api-docs
        name: 'Accounts Service APIs'
      - url: /notification-service/api/v3/api-docs
        name: 'Notifications Service APIs'

management:
  info:
    build:
      enabled: true
    os:
      enabled: true
    defaults:
      enabled: true
    java:
      enabled: true
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:

  instance:
    instance-id: gateway
    app-group-name: justedlev-hub
    appname: gateway
  client:
    service-url:
      defaultZone: ${SERVICE_REGISTRY}

logging:
  level:
    web: trace
    org:
      springframework:
        security: trace

# Custom properties
keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI}
  jwk-set-uri: ${KEYCLOAK_JWKS_URI}
  introspection-uri: ${KEYCLOAK_INTROSPECTION_ENDPOINT}
  client:
    id: ${KEYCLOAK_CLIENT_ID}
    secret: ${KEYCLOAK_CLIENT_SECRET}
